package App::TriplejPlaysLocal::Tweets;

use autodie;
use Carp qw(croak);
use Method::Signatures 20140224;
use POSIX qw(strftime);
use Moo;
use MooX::HandlesVia;
use namespace::clean;

# ABSTRACT: Song Tweet Storage

# VERSION: Generated by DZP::OurPkg:Version

=head1 SYNOPSIS

    use App::TriplejPlaysLocal::Tweets;

    my $tweets = App::TriplejPlaysLocal::Tweets->new();

=head1 DESCRIPTION

Tweet Storage.

=cut

has 'songs' => (
  is          => 'rw',
  handles_via => 'Array',
  handles     => {
    push_val      => 'push',
    check_tweets  => 'first_index',
    get_tweet     => 'get',
    delete_tweet  => 'delete',
  },
  default     => sub { [ ] },
);

=method check_time

  $my $index = $tweets->check_time;

If there is a tweet for the current minute it will return the index
or '-1' if none found.

=cut

method check_time {
  my $time = strftime("%H:%M", localtime(time));
  return $self->check_tweets(sub { $_->time eq $time });
}

1;
