package App::TriplejPlaysLocal;

use 5.010;
use Method::Signatures 20140224;
use App::TriplejPlaysLocal::Twitter;
use App::TriplejPlaysLocal::Tweets;
use AnyEvent;
use EV;
use Moo;
use namespace::clean;

# ABSTRACT: Time Shifts @triplejplays

# VERSION: Generated by DZP::OurPkg:Version

=head1 SYNOPSIS

    use App::TriplejPlaysLocal;

    my $plays = App::TriplejPlaysLocal->new();

=head1 DESCRIPTION

Main App!

=cut

has '_tweets'   => ( is => 'rw', lazy => 1, builder => 1 );
has '_twitter'  => ( is => 'rw', lazy => 1, builder => 1 );

method _build__twitter {
  return App::TriplejPlaysLocal::Twitter->new(
    tweets => $self->_tweets,
  );
}

method _build__tweets {
  return App::TriplejPlaysLocal::Tweets->new();
}

method run {
  $self->get_tweets;
  $self->check_tweets;
}

method get_tweets {
  $self->_twitter->get_tweets;
}

method check_tweets {
  my $index = $self->_tweets->check_time;
  say $index;
  if ($index != -1) {
    say $self->_tweets->get($index)->build_tweet;
  }
}

1;
